networks:
  rabbitmq_network:
    external: true

services:
    app:
        build:
            context: ./app
        container_name: exchange_rate_service_no1
        networks:
            - rabbitmq_network
        ports:
            - 3004:3006

    app_2:
        build:
            context: ./app
        container_name: exchange_rate_service_no2
        networks:
            - rabbitmq_network
        ports:
            - 3005:3006
