networks:
  rabbitmq_network:
    external: true

services:
    app:
        build:
            context: ./app
        container_name: gold_price_service_no1
        networks:
            - rabbitmq_network
        ports:
            - 3008:3007

    app_2:
        build:
            context: ./app
        container_name: gold_price_service_no2
        networks:
            - rabbitmq_network
        ports:
            - 3009:3007

